TITLE = "CS7DS4 | Data Visualization 2020 | Assignment 3"
NAME = "Name: Rohan Dilip Bagwe"
TCD_ID = "TCDID: 19314431"
COURSE = "Course Title: Computer Science - Intelligent Systems"
MODULE = "Module: Data Visualization (CS7DS4)"
DESC = "PLAYER3SIXTY° a football player analysis dashboard is meant to be a resource that could help managers and scouts filter the top players across the world, compare and analyze them on various parameters and accordingly make a decision that would be worth the investment, time and commitment by the clubs and Managers. This dashboard helps coaches and scouts by providing simplified yet effective exploratory visualization tools to discover the most promising profiles and enables player agents to better understand their players’ strengths and weaknesses."
